import { computed } from "@vue/runtime-core"

export function modifyPanelLabors(panelLabors) {
    for (let i=0; i<panelLabors.length; i++) {
        let panelLabor = panelLabors[i]
        // add variables on top of data generated by API.
        panelLabor.base_hours = parseFloat(panelLabors[i].base_hours)
        panelLabor.base_add = 0
        panelLabor.base_option_add = 0
        panelLabor.option_add = 0
        panelLabor.total = computed(() => {
            return panelLabor.base_hours + 
                   panelLabor.base_add + 
                   panelLabor.base_option_add + 
                   panelLabor.option_add
        })
    }
}
